name: Deploy GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cargo install trunk || true \
            && rustup target add wasm32-unknown-unknown

      - name: Build the Rust WASM app and all of its assets
        run: trunk serve --public-url ${{ github.event.repository.name }}

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Deploy Pages
        uses: actions/deploy-pages@v1
