name: Deploy to github pages.

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clone json crate
      run: git clone https://github.com/RobinToncourt/json.git ../
    - name: Install cargo trunk
      run: cargo install --locked trunk
    - name: Build
      run: cargo build --verbose
    - name: Deploy
      run: trunk serve
