name: Deploy GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
    runs-on: ubuntu-latest

    checkout:
      steps:
          name: Checkout
          uses: actions/checkout@v3

    dependencies:
      steps:
          name: Install dependencies
          run: |
            cargo install trunk || true \
              && rustup target add wasm32-unknown-unknown

    build:
      steps:
          needs: checkout
          name: abc
          run: trunk build --public-url ${{ github.event.repository.name }}

    deploy:
      steps:
          needs: build
          name: Setup Pages
          uses: actions/configure-pages@v2
  
          name: Deploy_Pages
          uses: actions/deploy-pages@v1

  # deploy:
  #   needs: build
  #
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1
